### PR TITLE
Material onboarding

### PR DESCRIPTION
**Pull request by wispborne**
I love the app idea, it's something that will be useful to me for work. However, the UI design could be improved, starting with the tutorial. 

Here is a small update to the tutorial - it makes it interactive and takes the user through three steps quickly. 

You can of course choose to merge this, change it, or not merge it as you wish; it's your project. I won't be offended :)

### CODE REVIEW

**Comment by ManojMadanmohan** [comment]
Hi David, 

Thank you so much for the contribution! I agree with you, I am not good with design, and the design could be improved at a lot of places.

I've reviewed and tested this, all looks really good.

I was just wondering, can you replace the tutorial image in the readme with a .gif? If so, it would be nice to have all the tutorial-related changes merged in together, in one piece. If not, I'll merge this now and we can add that later.

Let me know, and I'll merge.

**Comment by wispborne** [comment]
Hey, I saw that you went and made the gif - looks good. 
Thanks for the Release tab, as well. 

I wanted some more freedom to make changes, [so I forked your project](https://github.com/davidwhitman/deep-link-launcher) and have been working on it for the last week. Mostly just UI updates and I moved the Firebase and Fabric code into a specialized build so you can use the app without them. It was nice to work off of a codebase that was already mature :)

**Comment by ManojMadanmohan** [comment]
Glad to have helped! :-)

There was a small issue that I came across on lower end devices with this after merging. I've made the fix (a67c5c4bdec9022a) and published these changes onto the play store. You should see them live in a few hours; Thanks again for contributing!

I checked out your fork, and it looks much better. I would have wished for you to merge it back here, but unfortunately I have no experience in kotlin and would not want to change this project to kotlin. 

Any further PRs in Java are still welcome though! Would be happy to merge and publish it.

**Comment by wispborne** [comment]
Ah, my bad, didn't test on old apis, but I've seen that bug before. 

Yeah, I didn't think that you would want all of the changes I wanted to make, which is why I ended up changing it from a true fork to a standalone repo. Speaking of changes, one of the first things I did was increase the minSDK to 21 ;) 

Any future PRs I'd make would probably just be for bug fixes, and I haven't found any (in fact I caused one, as you found).

**Pull request merged**
